config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # app/controlllers/usersにmapping
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/password',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'

  # 本人情報登録のモデルはUserInformationで、ユーザーひとりにつき１つだけなの で、resource で (resources ではありません)routing を定義します。resources :use r_informations で定義すると user_informations/1 のような id を params でとる URL が生成されます。本人情報登録の場合はログイン中のユーザーが判定できればよい。URLにidは不要です。
  resource :user_information # お互いに単数にする。

  # mail confirm
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
  # loginしていないとアクセスできないようにする（deviceの）
  before_action :authenticate_user!

  # userでアクセスできる。
  # 多対1 ひとつのuserに複数所持されている。
  belongs_to :user

  ZENKAKU_REGEXP = /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/
  ZENKAKU_KANA_REGEXP = /\A[ァ-ヶー－]+\z/

  # allow_blankで入力されなかった場合はerror messageが出ない。
  validates :family_name, format: { with: ZENKAKU_REGEXP, message: 'は全角で入力してください。'}, allow_blank: true
  validates :given_name, format: { with: ZENKAKU_REGEXP, message: 'は全角で入力してください。'}, allow_blank: true
  # presence オブジェクトが存在する場合はオブジェクト自身。ない場合はnilを返す
  # 入力必須とする。
  validates :family_name_kana, presence: true, format: { with: ZENKAKU_KANA_REGEXP, message: "は全角で入力してください" }, allow_blank: true

  validates :given_name_kana, format: { with: ZENKAKU_KANA_REGEXP, message: "は全角で入力してください" }, allow_blank: true
  validates :birth_date, presence :true
end

app/controllers/user_informations_controller.rb
class UserInformationsController < ApplicationController
  # has_oneを宣言すればbuild_アソシエーション名でcurrent_userのidがあらかじめ代入されているUserInformationモデルのインスタンスを生成することができる。
  def new
    @user_information = current_user.build_user_information
  end

  def create
    @user_information = current_user.build_user_information(user_information_params)

    if @user_information.save
      redirect_to :root, notice: "個人情報の登録に成功しました。"
    else
      flash.now.alert = "個人情報の登録に失敗しました。"
      render :new
    end
  end

  private

  # newやcreateのアクションメソッドではないのでprivateにする。
  def user_information_params
    params.require(:user_information).permit(
      :family_name,
      :given_name,
      :family_name_kana,
      :given_nama_kana,
      :birth_date
    )
  end
end

app/views/user_informations/create.html.erb
<div>
  <h1 class="font-bold text-4xl">UserInformations#create</h1>
  <p>Find me in app/views/user_informations/create.html.erb</p>
</div>

app/views/user_informations/new.html.erb
<main class="w-11/12 flex-1 max-w-screen-xl mx-auto bg-white mt-24 pb-24 md:px-8 xl:px-0" id="contents">
  <div class="text-center w-full px-4 bg-white md:w-2/3 lg:w-1/2 mx-auto" id="input">
    <h1 class="font-black mb-4 text-2xl">本人情報登録</h1>
    <div class="text-left mb-8">
      <div class="text-sm text-gray-600 mb-8">
        <p>安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。</p>
      </div>
    </div>
    <%= form_with model: @user_information, url: user_information_path do |f| %>
      <%= render partial: "shared/error_messages", locals: { resource: @user_information } %>
      <div class="text-left">
        <div class="mb-8">
          <%= f.label :family_name, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.text_field :family_name, class: "appearance-none border border-gray-300 rounded py-2 px-3 text-grey-darker w-full", placeholder: "例）売買" %>
        </div>
        <div class="mb-8">
          <%= f.label :given_name, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.text_field :given_name, class: "appearance-none border border-gray-300 rounded py-2 px-3 text-grey-darker w-full", placeholder: "例）太郎" %>
        </div>
        <div class="mb-8">
          <%= f.label :given_name_kana, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.text_field :given_name_kana, class: "appearance-none border border-gray-300 rounded py-2 px-3 text-grey-darker w-full", placeholder: "例）ウリカイ" %>
        </div>
        <div class="mb-8">
          <%= f.label :family_name_kana, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.text_field :family_name_kana, class: "appearance-none border border-gray-300 rounded py-2 px-3 text-grey-darker w-full", placeholder: "例）タロウ" %>
        </div>
        <div class="mb-8">
          <%= f.label :birth_date, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.date_field :birth_date, class: "appearance-none border border-gray-300 rounded py-2 px-3 text-grey-darker w-full", placeholder: "2021/12/12" %>
        </div>
      </div>
      <div>
        <div class="text-center mb-2 flex flex-col space-y-4">
          <%= f.submit "次へ", class: "text-base font-bold bg-red-500 text-white p-2 w-full block text-sm py-4 rounded-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</main>